name: Node (Lint + Format) CI

on: pull_request

jobs:
  build_and_test:
    name: Build and Test(Lint & UnitTest)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Dependency
        run: npm ci

      - name: Lint & Format
        run: |
          npm run lint
          npm run fmt-check

      - name: Vitest
        run: npm run test

      - name: Build
        run: npm run build
